name: Fetch data from TagInfo

on:
  schedule:
    - cron: '4 4 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'
      - name: Install dependencies
        run: pip install pipenv --user
      - name: Pull data
        run: ./run.sh
