name: Sort PR

on:
  pull_request:

jobs:
  sort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Sort the data
        run: ./sort.sh
